## pandas cheat sheet https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

In [1]:
import pandas as pd

## DataFrame 만들기

**DataFrame**은 pandas의 핵심 자료구조로, **2차원 표(테이블)** 형태입니다.

| 용어 | 설명 | 예시 |
|------|------|------|
| **행 (row)** | 가로줄, 하나의 관측값(데이터) | 한 학생의 성적 정보 |
| **열 (column)** | 세로줄, 데이터의 속성(변수) | 이름, 국어, 영어, 수학 |
| **인덱스 (index)** | 각 행의 식별자 | 기본값: 0, 1, 2, ... |

DataFrame을 만드는 방법은 **입력 데이터의 형태**에 따라 다양합니다. 아래 예제들을 직접 따라 쓰며 확인해 보세요!

### 다음 코드를 보고 아래에 다시 쓰고 실행하며 확인하세요!

In [2]:
df=pd.DataFrame([4,5,6],columns=['A'])       
df

   A
0  4
1  5
2  6

> **방법 1 — 1차원 리스트로 만들기**
> `[4, 5, 6]`처럼 1차원 리스트를 넣으면 **1개의 열**이 생성됩니다.       
> `columns=['A']`로 열 이름을 지정하며, 인덱스는 자동으로 **0, 1, 2**가 됩니다.

In [3]:
df=pd.DataFrame([4,5,6],columns=['A'])       
df

   A
0  4
1  5
2  6

In [4]:
df=pd.DataFrame([[4,7,10]])
df

   0  1   2
0  4  7  10

> **방법 2 — 2차원 리스트 (열 이름 없음)**
> `[[4, 7, 10]]`처럼 리스트 안에 리스트를 넣으면 **1개의 행, 3개의 열**이 생성됩니다.         
> 열 이름을 지정하지 않으면 자동으로 **0, 1, 2** 숫자가 열 이름이 됩니다.

In [5]:
df=pd.DataFrame([[4,7,10]])
df

   0  1   2
0  4  7  10

In [6]:
df=pd.DataFrame([[4,7,10]],columns=['A', 'B','C'])
df

   A  B   C
0  4  7  10

> **방법 3 — 2차원 리스트 + 열 이름 지정**
> `columns=['A', 'B', 'C']`로 열 이름을 명시적으로 지정합니다.

In [7]:
df=pd.DataFrame([[4,7,10]],columns=['A', 'B','C'])
df

   A  B   C
0  4  7  10

In [8]:
df=pd.DataFrame({'A': [4,5,6],
                 'B': [7,8,9],
                 'C': [10,11,12]})
df

   A  B   C
0  4  7  10
1  5  8  11
2  6  9  12

> **방법 4 — 딕셔너리(열 단위)로 만들기**    
> `{'열이름': [값들의 리스트]}` 형태입니다.        
> **키(key) = 열 이름**, **값(value) = 해당 열의 데이터 리스트**      
> 각 열을 독립적으로 정의할 수 있어 직관적입니다.

df=pd.DataFrame({'A': [4,5,6],
                 'B': [7,8,9],
                 'C': [10,11,12]})
df

In [9]:
df=pd.DataFrame([{'A': 4,
                  'B': 7,
                  'C': 10}])
df

   A  B   C
0  4  7  10

> **방법 5 — 딕셔너리 1개를 리스트로 감싸기 (1행)**
> 딕셔너리 하나를 리스트로 감싸면 **1개의 행**이 만들어집니다.      
> 딕셔너리의 키 → 열 이름, 딕셔너리의 값 → 해당 셀의 데이터

In [10]:
df=pd.DataFrame([{'A': 4,
                  'B': 7,
                  'C': 10}])
df

   A  B   C
0  4  7  10

In [11]:
df=pd.DataFrame([{'A': 4, 'B': 7,'C': 10},
                {'A': 5, 'B': 8,'C': 11},
                {'A': 6, 'B': 9,'C': 12}])
df

   A  B   C
0  4  7  10
1  5  8  11
2  6  9  12

> **방법 6 — 딕셔너리 리스트로 만들기 (가장 실용적!)**
> **딕셔너리 1개 = 행(row) 1개** 입니다.
> API 응답, JSON 파일 등 실제 데이터는 대부분 이 형태로 되어 있어, 실무에서 가장 많이 사용됩니다.        
> ```
> [{'A':4,'B':7,'C':10},   ← 0번 행
>  {'A':5,'B':8,'C':11},   ← 1번 행
>  {'A':6,'B':9,'C':12}]   ← 2번 행
> ```

In [12]:
df=pd.DataFrame([{'A': 4, 'B': 7,'C': 10},
                {'A': 5, 'B': 8,'C': 11},
                {'A': 6, 'B': 9,'C': 12}])
df

   A  B   C
0  4  7  10
1  5  8  11
2  6  9  12

### 하나의 열 선택

### 열(Column) 선택 방법 비교


| 코드 | 반환 타입 | 특징 |
|------|-----------|------|
| `df['A']` | **Series** | 가장 일반적인 방법, 항상 사용 가능 |
| `df.A` | **Series** | 열 이름이 단순한 문자열일 때만 가능 |
| `df[['A']]` | **DataFrame** | 대괄호 두 겹 → DataFrame 유지 |

> 주의:  `df['A']`와 `df[['A']]`의 차이를 꼭 기억하세요! 결과 타입이 다릅니다.

In [13]:
df

   A  B   C
0  4  7  10
1  5  8  11
2  6  9  12

In [14]:
df['A']      #df.A 로도 할 수 있음       #비교: df[['A']]

0    4
1    5
2    6
Name: A, dtype: int64

In [15]:
df['A']

0    4
1    5
2    6
Name: A, dtype: int64

In [16]:
df.A

0    4
1    5
2    6
Name: A, dtype: int64

In [17]:
df.A

0    4
1    5
2    6
Name: A, dtype: int64

In [18]:
df[[ 'A']]

   A
0  4
1  5
2  6

In [19]:
df[[ 'A']]

   A
0  4
1  5
2  6

### 여러 열 선택


여러 열을 동시에 선택할 때는 **대괄호 두 겹** `df[['열1', '열2']]`을 사용합니다.

```
df[['A', 'B']]
   ↑        ↑
   바깥 []   안쪽 []는 열 이름 리스트
```

- 안쪽 `[]`: 선택할 열 이름들의 **리스트**
- 바깥쪽 `[]`: DataFrame **인덱싱** 연산자
- 결과는 항상 **DataFrame** 형태로 반환됩니다!

In [20]:
df[['A','B']]

   A  B
0  4  7
1  5  8
2  6  9

In [21]:
df[['A','B']]

   A  B
0  4  7
1  5  8
2  6  9

### 하나의 행 선택

### 행(Row) 선택: loc 사용법

`df.loc[인덱스]`로 특정 행을 선택합니다.

- `loc`은 **라벨(label) 기반** 인덱싱입니다
- 기본 인덱스가 0, 1, 2...일 때 해당 숫자로 접근
- 결과는 **Series** 형태로 반환됩니다 (인덱스 = 열 이름, 값 = 해당 행의 데이터)

> 예: `df.loc[0]` → 0번 행의 데이터를 Series로 반환

In [22]:
df.loc[0]

A     4
B     7
C    10
Name: 0, dtype: int64

In [23]:
df.iloc[0]

A     4
B     7
C    10
Name: 0, dtype: int64

### 여러 행 선택


`df.loc[[인덱스1, 인덱스2]]`처럼 **리스트**로 여러 행을 선택합니다.

- 결과는 **DataFrame** 형태로 반환됩니다
- 연속된 행이 아니어도 됩니다! (예: 0번 행과 2번 행만 선택 가능)

In [24]:
df.loc[[0,2]]

   A  B   C
0  4  7  10
2  6  9  12

In [25]:
df.loc[[0,2]]

   A  B   C
0  4  7  10
2  6  9  12

In [26]:
df.iloc[[0,2]]

   A  B   C
0  4  7  10
2  6  9  12

In [27]:
df.iloc[[0,2]]

   A  B   C
0  4  7  10
2  6  9  12

### loc 사용하여 행 , 열 선택


`df.loc[행 선택, 열 선택]` 형태로 **행과 열을 동시에** 지정할 수 있습니다.

| 코드 | 의미 |
|------|------|
| `df.loc[:, 'A']` | **모든 행**, A열만 선택 |
| `df.loc[:, ['A','C']]` | **모든 행**, A열과 C열 선택 |
| `df.loc[1, ['A','C']]` | **1번 행**, A열과 C열 선택 |
| `df.loc[[0,1], ['A','C']]` | **0,1번 행**, A열과 C열 선택 |

>  `:` 는 "전체(all)"를 의미합니다 — 파이썬 슬라이싱과 동일한 개념!

In [28]:
df.loc[:, 'A']                                            # df.loc[:, ['A']]

0    4
1    5
2    6
Name: A, dtype: int64

In [29]:
df.loc[:, 'A']

0    4
1    5
2    6
Name: A, dtype: int64

In [30]:
df.loc[:, ['A','C']]

   A   C
0  4  10
1  5  11
2  6  12

In [31]:
df.loc[:, ['A','C']]

   A   C
0  4  10
1  5  11
2  6  12

In [32]:
df.loc[1, ['A','C']]

A     5
C    11
Name: 1, dtype: int64

In [33]:
df.loc[1, ['A','C']]

A     5
C    11
Name: 1, dtype: int64

In [34]:
df.loc[[0 ,1], ['A','C']]

   A   C
0  4  10
1  5  11

In [35]:
df.loc[[0 ,1], ['A','C']]

   A   C
0  4  10
1  5  11

### 조건을 만족하는 데이터 (하나의 데이터는 하나의 행) 선택 
#### 불리언(Boolean) 인덱싱 — 조건에 맞는 행만 필터링!

조건을 이용해 원하는 데이터만 골라내는 강력한 기능입니다.

**동작 원리 (2단계):**

1. **조건식** `df['A'] > 5` → 각 행에 대해 True / False 반환
2. **필터링** `df[조건]` → True인 행만 선택하여 반환

**여러 조건 조합:**
```python
df[(df['A'] > 4) & (df['B'] < 9)]   # AND 조건 (둘 다 만족)
df[(df['A'] < 5) | (df['C'] > 11)]  # OR 조건 (하나만 만족해도)
```

> 여러 조건을 쓸 때는 각 조건을 **소괄호 `()`로 반드시 감싸야** 합니다!

In [36]:
df['A']>5

0    False
1    False
2     True
Name: A, dtype: bool

In [37]:
df[df['A']>5]

   A  B   C
2  6  9  12

In [38]:
df.loc[df['A']>5]

   A  B   C
2  6  9  12

In [39]:
df.loc[df['A']>5]

   A  B   C
2  6  9  12

In [40]:
df.loc[df['A']>5, ['A','B']]

   A  B
2  6  9

In [41]:
df.loc[df['A']>5, ['A','B']]

   A  B
2  6  9

### 다음 코드의 data 변수에 들어있는 내용을 확인하세요! <br> 즉 딕셔너리 구조들을 모아놓은 리스트 구조입니다!!

In [42]:
data={'response': {'body': {'totalCount': 304,
   'items': [{'clearVal': '33',
     'sn': '2',
     'districtName': '경기',
     'dataDate': '2020-01-03',
     'issueVal': '82',
     'issueTime': '11:00',
     'clearDate': '2020-01-04',
     'issueDate': '2020-01-03',
     'moveName': '남부권',
     'clearTime': '17:00',
     'issueGbn': '주의보',
     'itemCode': 'PM25'},
    {'clearVal': '34',
     'sn': '5',
     'districtName': '전북',
     'dataDate': '2020-01-03',
     'issueVal': '81',
     'issueTime': '22:00',
     'clearDate': '2020-01-05',
     'issueDate': '2020-01-03',
     'moveName': '전주권역',
     'clearTime': '14:00',
     'issueGbn': '주의보',
     'itemCode': 'PM25'}],
   'pageNo': 1,
   'numOfRows': 900},
  'header': {'resultMsg': 'NORMAL_CODE', 'resultCode': '00'}}}

### data 변수의 구조 분석

위 `data`는 **중첩된 딕셔너리** 구조입니다. 실제 공공데이터 API 응답 형태입니다.

```
data
└── 'response'
    └── 'body'
        ├── 'totalCount': 304
        ├── 'items': [          ← **이 리스트가 우리가 원하는 데이터!**
        │   {딕셔너리1},        ← 미세먼지 주의보 첫 번째 기록
        │   {딕셔너리2}         ← 미세먼지 주의보 두 번째 기록
        │   ]
        └── 'pageNo': 1
    └── 'header'
        └── 'resultCode': '00'
```

DataFrame으로 만들려면 **items 리스트**까지 들어가야 합니다!!
```python
df = pd.DataFrame(data['response']['body']['items'])
```

### 위의 리스트 구조인 data 로 DataFrame을 만들고 df 로 지정

In [43]:
df=pd.DataFrame(data)
df

                                                 response
body    {'totalCount': 304, 'items': [{'clearVal': '33...
header   {'resultMsg': 'NORMAL_CODE', 'resultCode': '00'}

### 위 코드의 결과를 확인해 보세요!

`pd.DataFrame(data)`를 그대로 실행하면 원하는 표 형태가 나오지 않습니다.
`data`가 중첩된 딕셔너리이기 때문입니다.

**올바른 방법**: `items` 리스트까지 경로를 직접 지정해야 합니다.

```python
# 올바른 DataFrame 생성
df = pd.DataFrame(data['response']['body']['items'])
df
```

빈 셀에 위 코드를 작성하고 실행해서 제대로 된 표가 나오는지 확인해 보세요!

In [44]:
df =  pd.DataFrame(    data['response']['body']['items']   )
df

,clearVal,sn,districtName,dataDate,issueVal,issueTime,clearDate,issueDate,moveName,clearTime,issueGbn,itemCode
0,33,2,경기,2020-01-03,82,11:00,2020-01-04,2020-01-03,남부권,17:00,주의보,PM25
1,34,5,전북,2020-01-03,81,22:00,2020-01-05,2020-01-03,전주권역,14:00,주의보,PM25

In [45]:
df =  pd.DataFrame(    data['response']['body']['items']   )
df

,clearVal,sn,districtName,dataDate,issueVal,issueTime,clearDate,issueDate,moveName,clearTime,issueGbn,itemCode
0,33,2,경기,2020-01-03,82,11:00,2020-01-04,2020-01-03,남부권,17:00,주의보,PM25
1,34,5,전북,2020-01-03,81,22:00,2020-01-05,2020-01-03,전주권역,14:00,주의보,PM25